FROM node:20.10-alpine

ARG NODE_ENV
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_PASSWORD
ARG DATABASE_NAME

ENV NODE_ENV $NODE_ENV
ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV DATABASE_NAME $DATABASE_NAME

RUN npm i -g pnpm

WORKDIR /usr/src/app
COPY package.json ./
RUN pnpm install

COPY . .
EXPOSE 3000

CMD ["/bin/sh", "-c", "pnpm migration:run;pnpm start"]
