services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_BUILD_TARGET:-development} # Default to 'development'
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV:-development} # Default to 'development'
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: [CMD, curl, -f, 'http://api:3000/']
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: api.db.local
      POSTGRES_PASSWORD: api.db.local
      POSTGRES_DB: api
    ports:
      - '5432'
    healthcheck:
      test: [CMD-SHELL, pg_isready, -d, $DATABASE_NAME, -U, $DATABASE_USERNAME]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s
